export const ROUTES = {
  Admin: {
    Dashboard: "/admin/dashboard",
    Users: "/admin/users",
    Roles: "/admin/roles",
    Partners: "/admin/partners",
    PartnersOnboard: "/admin/partners/onboard",
    Restaurants: "/admin/restaurants",
    Menus: "/admin/menus",
    Riders: "/admin/riders",
    RidersOnboard: "/admin/riders/onboard",
    Orders: "/admin/orders",
    OrdersTracking: "/admin/orders/tracking",
    Deliveries: "/admin/deliveries",
    DeliveriesAssign: "/admin/deliveries/assign",
    Payments: "/admin/payments",
    PaymentsRefunds: "/admin/payments/refunds",
    Reviews: "/admin/reviews",
    Notifications: "/admin/notifications",
    Reports: "/admin/reports",
    Settings: "/admin/settings",
  },
  Partner: {
    Dashboard: "/partner/dashboard",
    Menu: "/partner/menu",
    MenuCategories: "/partner/menu/categories",
    MenuItems: "/partner/menu/items",
    OrdersActive: "/partner/orders/active",
    OrdersHistory: "/partner/orders/history",
    Restaurant: "/partner/restaurant",
    Earnings: "/partner/earnings",
    Reviews: "/partner/reviews",
    Notifications: "/partner/notifications",
  },
  Rider: {
    Dashboard: "/rider/dashboard",
    DeliveriesActive: "/rider/deliveries/active",
    DeliveriesHistory: "/rider/deliveries/history",
    Orders: "/rider/orders",
    Earnings: "/rider/earnings",
    Profile: "/rider/profile",
    Notifications: "/rider/notifications",
  },
  Customer: {
    Dashboard: "/customer/dashboard",
    Restaurants: "/customer/restaurants",
    OrdersActive: "/customer/orders/active",
    OrdersHistory: "/customer/orders/history",
    Payments: "/customer/payments",
    Reviews: "/customer/reviews",
    Profile: "/customer/profile",
    Notifications: "/customer/notifications",
    Help: "/customer/help",
  },
  Auth: {
    Login: "/login",
    Signup: "/signup",
    ForgotPassword: "/forgot-password",
    VerifyEmail: "/verify-email",
  },
} as const;
