export const PERMISSIONS = {
    VIEW_DASHBOARD: "view_dashboard",
    VIEW_USERS: "view_users",
    MANAGE_ROLES: "manage_roles",
    VIEW_ALL_PARTNERS: "view_all_partners",
    CREATE_PARTNERS: "create_partners",
    MANAGE_MENU: "manage_menu",
    VIEW_RIDERS: "view_riders",
    CREATE_RIDERS: "create_riders",
    VIEW_ALL_ORDERS: "view_all_orders",
    VIEW_ALL_DELIVERIES: "view_all_deliveries",
    ASSIGN_DELIVERIES: "assign_deliveries",
    VIEW_ALL_PAYMENTS: "view_all_payments",
    PROCESS_REFUNDS: "process_refunds",
    MODERATE_REVIEWS: "moderate_reviews",
    SEND_NOTIFICATIONS: "send_notifications",
    VIEW_REPORTS: "view_reports",
    MANAGE_SETTINGS: "manage_settings",
    VIEW_ORDERS: "view_orders",
    UPDATE_PARTNERS: "update_partners",
    VIEW_PAYMENTS: "view_payments",
    VIEW_REVIEWS: "view_reviews",
    VIEW_NOTIFICATIONS: "view_notifications",
    VIEW_DELIVERIES: "view_deliveries",
    CREATE_ORDERS: "create_orders",
    CREATE_REVIEWS: "create_reviews",
  } as const;